version: 0.2
env:
  secrets-manager:
    CREDENTIALS_GIT_REPO: ${secretsmanager_name}
phases:
  build:
    commands:
      - echo "Hello World"
      - varNew=`echo $CREDENTIALS_GIT_REPO | base64`
      - echo "Secrets value should be hidden by CodeBuild, the value is $CREDENTIALS_GIT_REPO"
      - echo "Secrets value base64 encoded is $varNew"
      - varNew=`echo $varNew | base64 --decode`
      - echo "Secrets value base64 encoded then decoded then is $varNew"
      - printenv
